GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "name": "This is new new",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT",
    "content": "This is important content 3"
}

###

DELETE http://localhost:3001/api/notes/1
